scrape_configs:
  - job_name: "dgraph"
    metrics_path: "/debug/prometheus_metrics"
    scrape_interval: "2s"
    static_configs:
      - targets:
          - zero:6080     # For Dgraph zero, 6080 is the http endpoint exposing metrics.
          - alpha:8080    # For Dgraph alpha, 8080 is the http endpoint exposing metrics.
          - alpha:8080
          - alpha:8080