{
 "title": "Crawler Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Api Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(client_api_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Http Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(request_duration_seconds_sum[1m])"
    }
   ]
  },
  {
   "title": "DNS & TLS latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dns_duration_seconds_sum[1m])"
    },
    {
     "expr": "rate(tls_duration_seconds_sum[1m])"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes{job=\"andromeda\"}[1m])"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"andromeda\"}[1m])"
    }
   ]
  },
  {
   "title": "Heap Allocations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"andromeda\"}",
     "legendFormat": "heap_alloc"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"andromeda\"}",
     "legendFormat": "heap_idle"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"andromeda\"}",
     "legendFormat": "head_inuse"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"andromeda\"}[1m])"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"andromeda\"}"
    }
   ]
  },
  {
   "title": "Get Items",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dynamodb_get_item_total[1m])"
    }
   ]
  },
  {
   "title": "Put Items",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dynamodb_put_item_total[1m])"
    }
   ]
  },
  {
   "title": "Put Item Already Exists",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dynamodb_put_item_condition_failed_total[1m])"
    }
   ]
  },
  {
   "title": "DynamoDB Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(dynamodb_latency_sum[1m])" }
   ]
  },
  {
   "title": "Transactions Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(transactions_total[1m])" }
   ]
  },
  {
   "title": "DGraph Commit Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(commit_latency_sum[1m])" }
   ]
  }
 ]
}