{
 "title": "General Overview Copy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "General Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(client_api_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes{job=\"andromeda\"}[1m])"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"andromeda\"}[1m])"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"andromeda\"}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"andromeda\"}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"andromeda\"}"
    }
   ]
  },
  {
   "title": "Crawler Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"andromeda\"}"
    }
   ]
  },
  {
   "title": "DGraph Mutations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(mutations_total[1m])" }
   ]
  },
  {
   "title": "DynamoDB Put",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dynamodb_put_item_total[1m])"
    }
   ]
  },
  {
   "title": "DynamoDB Get",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dynamodb_get_item_total[1m])"
    }
   ]
  },
  {
   "title": "DynamoDB Item Already Exists",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dynamodb_put_item_condition_failed_total[1m])"
    }
   ]
  },
  {
   "title": "SQS Send Message",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "QueueName": "andromeda-test-1" },
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "region": "us-east-1",
     "statistics": [ "SampleCount" ]
    }
   ]
  },
  {
   "title": "SQS Message Received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "QueueName": "andromeda-test-1" },
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "SQS Message Deleted",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "QueueName": "andromeda-test-1" },
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}