{
 "title": "Dgraph Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"dgraph\"}"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"dgraph\"}"
    }
   ]
  },
  {
   "title": "Memory Usage (internal)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "dgraph_memory_inuse_bytes" },
    { "expr": "dgraph_memory_idle_bytes" },
    { "expr": "dgraph_memory_proc_bytes" }
   ]
  },
  {
   "title": "Disk Usage - Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(badger_v2_read_bytes{job=\"dgraph\"}[1m])"
    },
    {
     "expr": "rate(badger_v2_written_bytes{job=\"dgraph\"}[1m])"
    }
   ]
  },
  {
   "title": "Disk Ops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(badger_v2_disk_reads_total{job=\"dgraph\"}[1m])"
    },
    {
     "expr": "rate(badger_v2_disk_writes_total{job=\"dgraph\"}[1m])"
    }
   ]
  },
  {
   "title": "Queries & Mutations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dgraph_num_queries_total{method=\"Server.Mutate\"}[1m])",
     "legendFormat": "Mutations"
    },
    {
     "expr": "rate(dgraph_num_queries_total{method=\"Server.Query\"}[1m])",
     "legendFormat": "Queries"
    }
   ]
  },
  {
   "title": "Concurrent Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"dgraph\"}"
    }
   ]
  }
 ]
}