apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
  - name: CloudWatch
    type: cloudwatch
    editable: true
    jsonData:
      authType: credentials
      defaultRegion: us-east-1
      profile: default